### ISSUE TITLE
FR: multiple-position and multilevel subsetting of lists

### ISSUE THREAD

**Issue by ramiromagno** [rossellhayes/crossmap#4]
Is it possible to perform multiple-position and multilevel subsetting of lists?

Or something like xpath for XML?

https://github.com/tidyverse/purrr/issues/977

Many thanks!

**Comment by rossellhayes** [comment]
Hi @ramiromagno, I'll have to think about the best way to fit this functionality into `crossmap`, but for right now, this function should work the way you're hoping:

``` r
new_pluck <- function(.x, ...) {
  new_pluck_impl(.x, indices = list(...))
}

new_pluck_impl <- function(.x, indices) {
  if (length(indices) > 0) {
    for (i in indices[[1]]) {
      .x[[i]] <- new_pluck_impl(.x[[i]], indices[-1])
    }
    
    .x <- .x[indices[[1]]]
  }
  
  .x
}
```

```r
obj1 <- list("a", list(1, elt = "foo"))
obj2 <- list("b", list(2, elt = "bar"))
x <- list(obj1, obj2)

result <- new_pluck(x, 1:2, 2)
str(result)
#> List of 2
#>  $ :List of 1
#>   ..$ :List of 2
#>   .. ..$    : num 1
#>   .. ..$ elt: chr "foo"
#>  $ :List of 1
#>   ..$ :List of 2
#>   .. ..$    : num 2
#>   .. ..$ elt: chr "bar"
```

<sup>Created on 2022-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ramiromagno** [comment]
Hi @rossellhayes,

Thanks for the quick reply!

This looks very promising. This would make traversing hierarchical data so much easier.

And do you think it would be possible to interpret missing arguments as select all? As we do usually with subsetting of matrices and dataframes. Something like:

```
new_pluck(x, , 2)
```

would select all elements at first level, and the second element at level 2.

**Comment by rossellhayes** [comment]
Good idea! This should do it:

``` r
new_pluck <- function(.x, ...) {
  indices <- rlang::dots_list(..., .preserve_empty = TRUE)
  new_pluck_impl(.x, indices)
}

new_pluck_impl <- function(.x, indices) {
  if (length(indices) == 0) {
    return(.x)
  }
    
  if (rlang::is_missing(indices[[1]])) {
    indices[[1]] <- seq_along(.x)
  }
  
  for (i in indices[[1]]) {
    .x[[i]] <- new_pluck_impl(.x[[i]], indices[-1])
  }
    
  .x[indices[[1]]]
}
```

```r
obj1 <- list("a", list(1, elt = "foo"))
obj2 <- list("b", list(2, elt = "bar"))
x <- list(obj1, obj2)

result <- new_pluck(x, , 2)
str(result)
#> List of 2
#>  $ :List of 1
#>   ..$ :List of 2
#>   .. ..$    : num 1
#>   .. ..$ elt: chr "foo"
#>  $ :List of 1
#>   ..$ :List of 2
#>   .. ..$    : num 2
#>   .. ..$ elt: chr "bar"
```

<sup>Created on 2022-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ramiromagno** [comment]
Wow! This is awesome!!

**Comment by rossellhayes** [comment]
@ramiromagno This is now available as the `xpluck()` function! You can check out #5 for more details. It should now be available if you install the dev version of `crossmap`.

**Comment by ramiromagno** [comment]
This is really good.

**Comment by rossellhayes** [comment]
@ramiromagno I just wanted to let you know that this functionality is now available in the CRAN release of `crossmap`!

**Comment by ramiromagno** [comment]
Great, thanks!
